import { Hotel, Utensils, MapPin, ShieldCheck, Mountain, Compass, Footprints, Timer } from "lucide-react";

export interface ItineraryDay {
  day: number;
  title: string;
  description: string;
  meals?: string;
  overnight?: string;
  highlights?: string[];
}

export interface PackageData {
  id: string;
  title: string;
  subtitle: string;
  image: string;
  heroImage: string;
  duration: string;
  groupSize: string;
  distance?: string;
  maxAltitude?: string;
  difficulty: string;
  bestSeason: string;
  startPoint: string;
  endPoint: string;
  overview: string;
  inclusions: { icon: any; text: string }[];
  exclusions: string[];
  itinerary: ItineraryDay[];
  highlights: string[];
  spiritualSignificance?: string;
  mandatoryItems?: string[];
  price?: string;
  category: string;
  nights: number;
}

export const packages: PackageData[] = [
  {
    id: "adi-kailash",
    title: "Adi Kailash & Om Parvat Yatra",
    subtitle: "5 Nights / 6 Days — Delhi to Delhi",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "5 Nights / 6 Days",
    category: "Adi Kailash",
    nights: 5,
    groupSize: "Group / Experiential",
    distance: "Round Trip",
    maxAltitude: "~5,500m",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Delhi",
    endPoint: "Delhi",
    overview: "Adi Kailash is believed to be the ancient earthly abode of Lord Shiva and Goddess Parvati, long before Mount Kailash became accessible. It is one of the five sacred Kailash peaks mentioned in Hindu scriptures. This yatra includes darshan of Adi Kailash, Parvati Sarovar, Om Parvat, and ancient temples along the route through the breathtaking landscapes of Uttarakhand.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "6 Breakfasts & 5 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Delhi to Pithoragarh",
        description: "Depart from Delhi at 6:00 AM, leaving behind the city's noise as you move towards the pure Himalayan air of Devbhoomi Uttarakhand. Along the way, flowing rivers, hidden waterfalls, and dense forests accompany the journey. On arrival in Pithoragarh, check in and relax. Nestled at 1,645 meters, Pithoragarh offers panoramic views of snow-capped Panchachuli Peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Panchachuli Peak views", "Himalayan forests", "River valleys"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "Drive to Dharchula along the sacred Kali River, with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages of Chialekh and Garbyang, passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Scenic off-roading"],
      },
      {
        day: 3,
        title: "Gunji/Nabhi to Adi Kailash & Back",
        description: "Start early and trek toward the sacred Adi Kailash, a powerful abode of Lord Shiva. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat, each steeped in ancient legends. At Adi Kailash Temple, perform prayers and take a holy dip in Parvati Sarovar. En route, marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi to Om Parvat & Mount Kailash Darshan",
        description: "Head to Om Parvat, where the snow naturally forms the sacred ॐ symbol. Enjoy darshan and meditation with stunning views. Visit Shri Nag Parvat and stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh/Dharchula",
        highlights: ["Om Parvat Darshan", "Mount Kailash view", "Hawan Puja", "Vyas Gufa"],
      },
      {
        day: 5,
        title: "Dharchula → Pithoragarh → Jageshwar Dham",
        description: "Early departure through scenic Himalayan landscapes. Visit Nepal Border at Dharchula, Kamakhya Mandir, Jateshwar Mahadev (ancient Shiva temple), and Chitai Golu Devta Mandir (famous for wish fulfillment). Evening arrival at Jageshwar Dham — explore ancient temples and attend evening aarti.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham",
        highlights: ["Kamakhya Mandir", "Jateshwar Mahadev", "Chitai Golu Devta", "Jageshwar Dham Aarti"],
      },
      {
        day: 6,
        title: "Jageshwar Dham → Kainchi Dham → Delhi",
        description: "Visit Jageshwar Jyotirling, Maa Jageshwari Shakti Peeth, Mrityunjay Mandir, Kuber Mandir, and Kainchi Dham (Neem Karoli Baba's ashram). Return journey to Delhi with divine blessings.",
        meals: "Breakfast",
        overnight: "Journey concludes",
        highlights: ["Jageshwar Jyotirling", "Mrityunjay Mandir", "Kainchi Dham", "Kuber Mandir"],
      },
    ],
    highlights: [
      "Darshan of Adi Kailash (Chhota Kailash)",
      "Om Parvat — Natural ॐ snow formation",
      "Holy dip in Parvati Sarovar",
      "Jageshwar Dham & ancient temples",
      "Scenic drive through Uttarakhand Himalayas",
      "Kainchi Dham — Neem Karoli Baba's ashram",
    ],
    spiritualSignificance: "Adi Kailash is believed to be the ancient earthly abode of Lord Shiva and Goddess Parvati. The sacred sites include Parvati Sarovar (meditation place of Goddess Parvati), Gauri Kund, Brahma Parvat, Nag Parvat, Kunti Parvat, and Pandav Qilla. Om Parvat is globally famous for the natural snow formation of the sacred 'ॐ' symbol on its face.",
  },
  {
    id: "adi-kailash-2n3d-dharchula",
    title: "Adi Kailash Express Yatra",
    subtitle: "2 Nights / 3 Days — Dharchula to Dharchula",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "2 Nights / 3 Days",
    category: "Adi Kailash",
    nights: 2,
    groupSize: "Group / Experiential",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Dharchula",
    endPoint: "Dharchula",
    overview: "The fastest way to experience the divine darshan of Adi Kailash and Om Parvat — designed for pilgrims who already have their permits or are arriving at Dharchula. Starting from Dharchula, this compact 2N/3D yatra covers Nabhi/Gunji, Adi Kailash Darshan with Parvati Sarovar & Gauri Kund, and Om Parvat darshan with a Hawan Puja at Kala Pani. Perfect for devotees seeking the sacred darshan efficiently.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "2 Breakfasts & 2 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained local vehicle with all permits" },
      { icon: ShieldCheck, text: "All Interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Dharchula → Nabhi / Gunji (Permit Day)",
        description: "Pilgrims arrive at Dharchula early in the morning. Complete Mandatory Government Formalities: Inner Line Permit (ILP), Medical Check-up, and Police Verification — compulsory for entry into Vyas Valley, a restricted border zone near the Indo-Tibet frontier. After permit completion, afternoon departure for Nabhi/Gunji by approved local vehicle. Nabhi and Gunji are ancient Himalayan villages along the Kali River, traditionally linked with Sage Vyas and the Mahabharata era, serving as the operational base for Adi Kailash and Om Parvat Yatra.",
        meals: "Dinner",
        overnight: "Nabhi / Gunji / Napalchu Homestay",
        highlights: ["Inner Line Permit formalities", "Kali River valley", "Ancient Himalayan villages"],
      },
      {
        day: 2,
        title: "Nabhi/Gunji → Adi Kailash → Nabhi/Gunji",
        description: "Start early from Gunji/Napalchu/Nabhi to Jyolingkong, then trek toward the sacred Adi Kailash. Along the way, witness Kunti Parvat, Pandav Fort, and Brahma Parvat, each steeped in ancient legends and spiritual energy. At Adi Kailash Temple, perform prayers to Lord Shiva and Goddess Parvati, and take a holy dip in Parvati Sarovar if time and health permit. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Conclude with a visit to Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar holy dip", "Gauri Kund", "Manokamna Temple", "Kunti Parvat", "Brahma Parvat"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Om Parvat → Dharchula",
        description: "After breakfast, head to Om Parvat where the snow naturally forms the sacred ॐ symbol. Devotees enjoy darshan and meditation while taking in the stunning views of Nabhi Parvat. On the way back, visit Shri Nag Parvat and stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted by authorities, view Mount Kailash from Old Lipulekh Pass. Return to Dharchula with divine blessings.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Dharchula",
        highlights: ["Om Parvat ॐ Darshan", "Mount Kailash view", "Hawan Puja at Kala Pani", "Vyas Gufa", "Kali Mandir"],
      },
    ],
    highlights: [
      "Adi Kailash Darshan — Ancient Abode of Lord Shiva",
      "Om Parvat — Natural ॐ snow formation miracle",
      "Holy dip in Parvati Sarovar",
      "Hawan Puja at sacred Kala Pani",
      "Kunti Parvat, Brahma Parvat & Pandav Fort",
      "Compact 3-day spiritual package from Dharchula",
    ],
    spiritualSignificance: "Adi Kailash is believed to be the ancient earthly abode of Lord Shiva and Goddess Parvati. The sacred sites include Parvati Sarovar (meditation & bathing place of Goddess Parvati), Gauri Kund (where Goddess Parvati performed penance), Brahma Parvat (associated with Lord Brahma), Nag Parvat (named after Sheshnag), and Pandav Qilla. Om Parvat is globally famous for the natural snow formation of the sacred ॐ symbol on its face — a rare miracle of nature and spirituality combined.",
  },
  {
    id: "adi-kailash-5n6d-kathgodam",
    title: "Adi Kailash Yatra — Kathgodam",
    subtitle: "5 Nights / 6 Days — Haldwani/Kathgodam to Kathgodam",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "5 Nights / 6 Days",
    category: "Adi Kailash",
    nights: 5,
    groupSize: "Group / Experiential",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Haldwani / Kathgodam",
    endPoint: "Haldwani / Kathgodam",
    overview: "A complete Adi Kailash Yatra starting from Haldwani/Kathgodam covering the divine darshan of Adi Kailash, Om Parvat, and an extended spiritual sightseeing of Kasar Devi Temple (rare Van Allen Belt energy zone), Katarmal Sun Temple (older than Konark), Jageshwar Dham, and Kainchi Dham. This 5N/6D package is ideal for devotees traveling from Kumaon region.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "6 Breakfasts & 5 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Haldwani/Kathgodam → Pithoragarh",
        description: "Depart from Haldwani/Kathgodam at 7:30 AM, moving towards the pure Himalayan air of Devbhoomi Uttarakhand. En route, visit Kasar Devi Temple — one of Earth's rare Van Allen Belt energy zones, once visited by Swami Vivekananda — and Katarmal Sun Temple, believed to be 400 years older than Konark. Arrive at Pithoragarh (1,645 m), nestled with panoramic views of snow-capped Panchachuli Peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Kasar Devi Temple (Van Allen Belt energy zone)", "Katarmal Sun Temple (older than Konark)", "Panchachuli Peak views"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "After breakfast, drive to Dharchula along the Kali River with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages of Chialekh and Garbyang, passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route. Arrive at Nabhi/Gunji Village, check in to homestay and rest.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Inner Line Permit"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Adi Kailash & Back",
        description: "Start early from Gunji/Napalchu/Nabhi to Jyolingkong, then trek toward the sacred Adi Kailash. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat. At Adi Kailash Temple, perform prayers to Lord Shiva and Goddess Parvati and take a holy dip in Parvati Sarovar. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Visit Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi → Om Parvat → Dharchula",
        description: "Head to Om Parvat, where the snow naturally forms the sacred ॐ symbol. Enjoy darshan and meditation. Visit Shri Nag Parvat and stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass. Return to Dharchula.",
        meals: "Breakfast & Dinner",
        overnight: "Dharchula",
        highlights: ["Om Parvat ॐ Darshan", "Hawan Puja at Kala Pani", "Vyas Gufa", "Nepal border at Dharchula"],
      },
      {
        day: 5,
        title: "Dharchula → Kamakhya → Jageshwar Dham",
        description: "Early departure from Dharchula through scenic Himalayan landscapes toward Pithoragarh. Stops: Nepal Border at Dharchula, Kamakhya Mandir (revered Shaktipeeth), Jateshwar Mahadev (ancient Shiva temple where Lord Shiva meditated after Maa Sati's sacrifice), and Chitai Golu Devta Mandir (famous for wish fulfillment). Evening arrival at Jageshwar Dham — explore ancient temples, attend evening aarti.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham",
        highlights: ["Kamakhya Mandir", "Jateshwar Mahadev", "Chitai Golu Devta Mandir", "Jageshwar Dham Evening Aarti"],
      },
      {
        day: 6,
        title: "Jageshwar Dham → Kainchi Dham → Kathgodam",
        description: "After breakfast, visit Jageshwar Dham — a peaceful valley of 124+ ancient Shiva temples amidst deodar forests, believed to be the origin of Shiva worship and the Maha Mrityunjaya Mantra. Temple Darshan: Mrityunjay Temple, Maa Jageshwari Shakti Peeth, Kuber Temple, Vridh Jageshwar, and Dandeshwar Mahadev. En route to Kainchi Dham, the sacred ashram of Neem Karoli Baba. Return to Haldwani/Kathgodam with divine blessings.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Haldwani/Kathgodam",
        highlights: ["Jageshwar Jyotirling", "Mrityunjay Mandir", "Kuber Mandir", "Kainchi Dham", "Dandeshwar Mahadev"],
      },
    ],
    highlights: [
      "Darshan of Adi Kailash (Chhota Kailash)",
      "Om Parvat — Natural ॐ snow formation",
      "Kasar Devi — Rare Van Allen Belt energy zone",
      "Katarmal Sun Temple — Older than Konark",
      "Jageshwar Dham — 124+ ancient Shiva temples",
      "Kainchi Dham — Neem Karoli Baba's sacred ashram",
    ],
    spiritualSignificance: "Adi Kailash is believed to be the ancient earthly abode of Lord Shiva and Goddess Parvati. Kasar Devi lies on one of the three known Van Allen Belt energy zones on Earth — a place once visited by Swami Vivekananda for meditation, known for its natural calm and magnetic spiritual vibrations. The Katarmal Sun Temple is believed to be 400 years older than the Konark Sun Temple. Jageshwar Dham is believed to be the place where Shiva Linga worship began.",
  },
  {
    id: "adi-kailash-6n7d-delhi",
    title: "Adi Kailash Yatra — Delhi (6N/7D)",
    subtitle: "6 Nights / 7 Days — Delhi to Delhi",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "6 Nights / 7 Days",
    category: "Adi Kailash",
    nights: 6,
    groupSize: "Group / Experiential",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Delhi",
    endPoint: "Delhi",
    overview: "A comprehensive 6N/7D Adi Kailash Yatra from Delhi covering the complete spiritual circuit: Kasar Devi Temple, Adi Kailash Darshan with Parvati Sarovar, Om Parvat with ॐ snow formation, Narayan Ashram visit, Panchachuli Range views, Jageshwar Dham's 124+ ancient temples, and Kainchi Dham. One of the most detailed Adi Kailash itineraries covering both the divine darshan and the cultural/spiritual richness of Kumaon.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "7 Breakfasts & 6 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Delhi → Pithoragarh",
        description: "Depart from Delhi at 7:30 AM towards the pure Himalayan air of Devbhoomi Uttarakhand. Along the way, flowing rivers, hidden waterfalls, and dense forests accompany the journey. En route, visit Kasar Devi Temple (Van Allen Belt energy zone) and Katarmal Sun Temple. Arrive at Pithoragarh (1,645 m) with panoramic views of snow-capped Panchachuli Peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Kasar Devi Temple", "Katarmal Sun Temple", "Panchachuli Peak views"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "Drive to Dharchula along the Kali River with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages, passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route. Arrive at Nabhi/Gunji Village.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Inner Line Permit"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Adi Kailash & Back",
        description: "Start early and trek toward the sacred Adi Kailash. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat. At Adi Kailash Temple, perform prayers and take a holy dip in Parvati Sarovar. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Visit Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi → Om Parvat → Narayan Ashram",
        description: "Head to Om Parvat where the snow forms the sacred ॐ symbol. Enjoy darshan and meditation. Visit Shri Nag Parvat and Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass. Drive to Narayan Ashram — a serene Himalayan retreat set amidst serene valleys and forests.",
        meals: "Breakfast & Dinner",
        overnight: "Narayan Ashram",
        highlights: ["Om Parvat ॐ Darshan", "Hawan Puja at Kala Pani", "Vyas Gufa", "Narayan Ashram"],
      },
      {
        day: 5,
        title: "Narayan Ashram → Panchachuli View → Dharchula",
        description: "Early morning visit to Narayan Ashram campus. After breakfast, check out and drive via Tawaghat. En route stop at Panchachuli Range View Point for photographs. Continue to Dharchula for evening arrival. Kali River sidewalk, local market exploration, and Nepal Darchula visit (time permitting).",
        meals: "Breakfast & Dinner",
        overnight: "Dharchula",
        highlights: ["Narayan Ashram campus", "Panchachuli Range View", "Kali River sidewalk", "Nepal Darchula"],
      },
      {
        day: 6,
        title: "Dharchula → Kamakhya → Jageshwar Dham",
        description: "Early departure through scenic Himalayan landscapes. Stops: Nepal Border at Dharchula, Kamakhya Mandir (revered Shaktipeeth), Jateshwar Mahadev (Ancient Shiva temple), and Chitai Golu Devta Mandir. Evening arrival at Jageshwar Dham — explore ancient temples and attend evening aarti.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham",
        highlights: ["Kamakhya Mandir", "Jateshwar Mahadev", "Chitai Golu Devta", "Jageshwar Dham Aarti"],
      },
      {
        day: 7,
        title: "Jageshwar Dham → Kainchi Dham → Delhi",
        description: "After breakfast, visit Jageshwar Dham — 124+ ancient Shiva temples in deodar forests, origin of Shiva worship and Maha Mrityunjaya Mantra. Temple Darshan: Mrityunjay Temple, Maa Jageshwari Shakti Peeth, Kuber Temple, Vridh Jageshwar, and Dandeshwar Mahadev. En route to Kainchi Dham (Neem Karoli Baba's ashram). Return to Delhi with divine blessings.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Delhi",
        highlights: ["Jageshwar Jyotirling", "Mrityunjay Mandir", "Kuber Mandir", "Kainchi Dham", "Vridh Jageshwar"],
      },
    ],
    highlights: [
      "Darshan of Adi Kailash (Chhota Kailash)",
      "Om Parvat — Natural ॐ snow formation",
      "Narayan Ashram — Himalayan spiritual retreat",
      "Panchachuli Range View",
      "Jageshwar Dham — 124+ ancient Shiva temples",
      "Kainchi Dham — Neem Karoli Baba's sacred ashram",
    ],
    spiritualSignificance: "Adi Kailash is the ancient earthly abode of Lord Shiva and Goddess Parvati. Narayan Ashram is a serene Himalayan retreat for meditation and spiritual reflection. The five Panchachuli peaks are sacred in Hindu mythology, linked to the Pandavas. Jageshwar Dham is the place where Shiva Linga worship began. Kainchi Dham is Neem Karoli Baba's divine ashram offering guru's grace and inner peace.",
  },
  {
    id: "adi-kailash-7n8d-delhi-munsiyari",
    title: "Adi Kailash & Munsiyari Yatra",
    subtitle: "7 Nights / 8 Days — Delhi to Delhi",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "7 Nights / 8 Days",
    category: "Adi Kailash",
    nights: 7,
    groupSize: "Group / Spiritual",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Delhi",
    endPoint: "Delhi",
    overview: "An extended 7N/8D Adi Kailash Yatra that uniquely combines the divine darshan of Adi Kailash and Om Parvat with a scenic detour to Munsiyari — the 'Little Kashmir of Kumaon' nestled beneath the majestic Panchachuli peaks — and the mystical Patal Bhuvneshwar cave temple. A perfect blend of spiritual blessings, natural beauty, and Himalayan adventure.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "8 Breakfasts & 7 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained Ertiga/Traveller vehicle" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Delhi → Pithoragarh",
        description: "Depart from Delhi at 6:00 AM towards Devbhoomi Uttarakhand. Flowing rivers, hidden waterfalls, and dense forests accompany the journey as the air grows fresher and the mind calmer. Arrive at Pithoragarh (1,645 m) — nestled with panoramic views of snow-capped Panchachuli Peaks, lush valleys, and sacred Himalayan silence.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Panchachuli Peak views", "Himalayan forests", "Sacred Himalayan air"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "Drive to Dharchula along the sacred Kali River with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages of Chialekh and Garbyang, passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route. Arrive at Nabhi/Gunji Village.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Inner Line Permit"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Adi Kailash & Back",
        description: "Start early and trek toward the sacred Adi Kailash. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat. At Adi Kailash Temple, perform prayers and take a holy dip in Parvati Sarovar. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Visit Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi → Om Parvat → Dharchula/Pithoragarh",
        description: "Head to Om Parvat where the snow naturally forms the sacred ॐ symbol. Enjoy darshan and meditation with stunning views. Visit Shri Nag Parvat and stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass. Return to Pithoragarh/Dharchula.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh/Dharchula",
        highlights: ["Om Parvat ॐ Darshan", "Hawan Puja at Kala Pani", "Vyas Gufa", "Mount Kailash view"],
      },
      {
        day: 5,
        title: "Dharchula → Munsiyari",
        description: "After breakfast, early morning departure from Dharchula (940 m) towards Munsiyari (2,200 m), ascending through serene Himalayan valleys. Arrive Munsiyari — nestled beneath the majestic Panchachuli peaks. Visit Maa Nanda Devi Temple, explore the Tribal Museum, and enjoy a walk through the local market. Evening: witness a magical sunset over Panchachuli peaks. Optional excursion towards Khaliya Top (3,500 m). Bonfire & dinner.",
        meals: "Breakfast & Dinner",
        overnight: "Munsiyari",
        highlights: ["Maa Nanda Devi Temple", "Panchachuli sunset views", "Tribal Museum", "Optional Khaliya Top trek"],
      },
      {
        day: 6,
        title: "Munsiyari → Patal Bhuvneshwar",
        description: "After breakfast, depart from Munsiyari. En route: Kalamuni Top (2,750 m) — a serene high pass with soul-stirring Himalayan views; Birthi Waterfall (2,000 m) — a majestic cascade with refreshing energy. Proceed for Patal Bhuvneshwar Cave Temple darshan (1,350 m) — a mystical cave shrine described in the Skanda Purana, believed to house divine forms of Lord Shiva. A single darshan here holds spiritual significance equivalent to Char Dham yatra.",
        meals: "Breakfast & Dinner",
        overnight: "Patal Bhuvneshwar",
        highlights: ["Kalamuni Top views", "Birthi Waterfall", "Patal Bhuvneshwar Cave Temple", "Char Dham spiritual merit"],
      },
      {
        day: 7,
        title: "Patal Bhuvneshwar → Jageshwar / Almora",
        description: "After breakfast, proceed towards Jageshwar Dham/Almora. En route, darshan at Haath Kalika Mandir, Gangolihat — a powerful Shaktipeeth with deep spiritual energy. Explore Almora Market and visit Maa Kasar Devi Temple. Continue to Jageshwar Dham — a sacred cluster of 125 ancient temples including Mrityunjay Mahadev, Maa Jageshwari Shaktipeeth, Kuber Mandir, and the mystical Ehrawat (Airavat) Cave, all set amidst dense deodar forests.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham / Almora",
        highlights: ["Haath Kalika Mandir Gangolihat", "Maa Kasar Devi Temple", "Jageshwar Dham 125 temples", "Mrityunjay Mahadev"],
      },
      {
        day: 8,
        title: "Jageshwar/Almora → Delhi",
        description: "After breakfast, begin the return from Jageshwar with Mahadev's shanti in your heart. Seek a peaceful darshan at Vridh Jageshwar. Pause at the serene lake of Bhimtal, where nature offers a moment of stillness. Feel the sacred energy at Kainchi Dham, a place filled with grace and quiet blessings. Continue towards Delhi carrying the essence of the Himalayas within.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Delhi",
        highlights: ["Vridh Jageshwar", "Bhimtal Lake", "Kainchi Dham", "Divine blessings"],
      },
    ],
    highlights: [
      "Adi Kailash Darshan & Parvati Sarovar holy dip",
      "Om Parvat — Natural ॐ snow formation",
      "Munsiyari — Little Kashmir with Panchachuli views",
      "Patal Bhuvneshwar — Mystical underground cave temple",
      "Jageshwar Dham — 125 ancient Shiva temples",
      "Haath Kalika Mandir & Kasar Devi spiritual circuit",
    ],
    spiritualSignificance: "This yatra connects multiple divine spiritual sites. Adi Kailash is the ancient abode of Lord Shiva. Patal Bhuvneshwar is a mystical cave shrine described in the Skanda Purana where a single darshan grants punya equivalent to Char Dham yatra. Haath Kalika Mandir is a powerful Shaktipeeth. Jageshwar Dham with 125 ancient temples is believed to be the place where Shiva Linga worship originated. Kainchi Dham is Neem Karoli Baba's divine ashram.",
  },
  {
    id: "adi-kailash-8n9d-delhi-panchachuli",
    title: "Adi Kailash & Panchachuli Expedition",
    subtitle: "8 Nights / 9 Days — Delhi to Delhi",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "8 Nights / 9 Days",
    category: "Adi Kailash",
    nights: 8,
    groupSize: "Group / Experiential",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Delhi",
    endPoint: "Delhi",
    overview: "The most immersive Adi Kailash experience — an 8N/9D expedition that combines the divine darshan of Adi Kailash, Om Parvat, and a unique trek into the Panchachuli Valley via Narayan Ashram, visiting remote Himalayan villages of Dugtu, Dantu, and Dharmavalli. Experience the Panchachuli Base Area trek, mystical Patal Bhuvneshwar cave, Gangolihat's ancient temples, Chitai Golju, Binsar Mahadev, Baijnath Dham, and Jageshwar Dham.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "9 Breakfasts & 8 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Delhi → Pithoragarh",
        description: "Depart from Delhi at 6:00 AM towards the pure Himalayan air of Devbhoomi Uttarakhand. Along the way, flowing rivers, hidden waterfalls, and dense forests accompany the journey. Arrive at Pithoragarh (1,645 m) — offering panoramic views of snow-capped Panchachuli Peaks, lush valleys, and sacred Himalayan silence.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Panchachuli Peak views", "Himalayan forests", "Sacred river valleys"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "Drive to Dharchula along the Kali River with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route. Arrive at Nabhi/Gunji Village.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Inner Line Permit"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Adi Kailash & Back",
        description: "Start early and trek toward the sacred Adi Kailash. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat. At Adi Kailash Temple, perform prayers and take a holy dip in Parvati Sarovar. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Visit Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi → Om Parvat → Narayan Ashram",
        description: "Head to Om Parvat where the snow forms the sacred ॐ symbol. Enjoy darshan and meditation. Visit Shri Nag Parvat and stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass. Drive to Narayan Ashram in serene valleys and forests.",
        meals: "Breakfast & Dinner",
        overnight: "Narayan Ashram",
        highlights: ["Om Parvat ॐ Darshan", "Hawan Puja at Kala Pani", "Vyas Gufa", "Narayan Ashram"],
      },
      {
        day: 5,
        title: "Narayan Ashram → Panchachuli Valley (Dharmavalli/Dugtu)",
        description: "Early morning explore the Narayan Ashram campus, library & gardens. After breakfast, drive and short trek to Dugtu/Dantu/Dharmavalli to enter Panchachuli Valley. Enjoy village life & mountain views. First views of the magnificent Panchachuli Peaks from the valley.",
        meals: "Breakfast & Dinner",
        overnight: "Dharmavalli / Dugtu Homestay",
        highlights: ["Narayan Ashram campus", "Panchachuli Peaks first view", "Traditional Himalayan villages", "Panchachuli Valley entry"],
      },
      {
        day: 6,
        title: "Panchachuli Base Area Trek",
        description: "Early morning easy hike towards the Panchachuli Base Area for close views of Panchachuli I–V Peaks. Photography, nature walks, and local interaction. Surrounded by glacier views, alpine meadows, and untouched Himalayan nature.",
        meals: "Breakfast & Dinner",
        overnight: "Dharmavalli / Dugtu",
        highlights: ["Panchachuli I-V Base Views", "Glacier views", "Alpine meadows", "Nature photography"],
      },
      {
        day: 7,
        title: "Dharmavalli → Dharchula → Patal Bhuvaneshwar → Gangolihat",
        description: "After breakfast, begin journey through serene Himalayan valleys. Dharchula: Witness the sacred India-Nepal border & Mahakali River confluence. Patal Bhuvaneshwar: Explore the mystical Shiva cave with ancient rock shrines, described in the Skanda Purana. Gangolihat: Visit ancient temples & soak in panoramic Himalayan peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Gangolihat",
        highlights: ["Dharchula India-Nepal border", "Patal Bhuvaneshwar Cave", "Gangolihat temples", "Mahakali River confluence"],
      },
      {
        day: 8,
        title: "Gangolihat → Chitai Golu Devta → Jageshwar Dham",
        description: "After breakfast at Gangolihat, pass through Chitai Golju — peaceful river valleys perfect for photography & light meditation. Binsar Mahadev — sacred temple in pine forests with misty mountains & spiritual vibes. Baijnath Dham — ancient Shiva temple with Himalayan river backdrop. Arrive at Jageshwar Dham — over 100 ancient temples in cedar forests with a divine evening aura.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham",
        highlights: ["Chitai Golju Devta", "Binsar Mahadev", "Baijnath Dham", "Jageshwar Dham 100+ temples"],
      },
      {
        day: 9,
        title: "Jageshwar Dham → Kainchi Dham → Delhi",
        description: "After breakfast, visit Jageshwar Dham — peaceful valley of 124+ ancient Shiva temples, origin of Maha Mrityunjaya Mantra. Temple Darshan: Maha Mrityunjaya Temple, Maa Jageshwari Shakti Peeth, and Kuber Temple. Scenic drive to Kainchi Dham — Neem Karoli Baba's sacred ashram. Return to Delhi with peace and divine blessings.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Delhi",
        highlights: ["Jageshwar Dham temples", "Maha Mrityunjaya Temple", "Kainchi Dham", "Return with divine blessings"],
      },
    ],
    highlights: [
      "Adi Kailash Darshan & Parvati Sarovar holy dip",
      "Om Parvat — Natural ॐ snow formation",
      "Panchachuli Valley trek via Narayan Ashram",
      "Patal Bhuvaneshwar — Mystical underground cave temple",
      "Chitai Golju, Binsar Mahadev & Baijnath Dham",
      "Jageshwar Dham — 124+ ancient Shiva temples",
    ],
    spiritualSignificance: "This 9-day yatra is a complete Himalayan spiritual circuit. Adi Kailash is Lord Shiva's earthly abode. Narayan Ashram offers deep meditation and spiritual reflection. Panchachuli's five peaks are sacred in Hindu mythology, linked to the Pandavas. Patal Bhuvaneshwar's single darshan equals Char Dham punya. Chitai Golju Devta is the God of Justice. Baijnath Dham and Jageshwar Dham are ancient Shiva temples of deep significance.",
  },
  {
    id: "adi-kailash-9n10d-delhi-extended",
    title: "Grand Adi Kailash Yatra",
    subtitle: "9 Nights / 10 Days — Delhi to Delhi",
    image: "/images/adi-kailash.jpg",
    heroImage: "/images/adi-kailash.jpg",
    duration: "9 Nights / 10 Days",
    category: "Adi Kailash",
    nights: 9,
    groupSize: "Group / Experiential",
    difficulty: "Moderate to Difficult",
    bestSeason: "May – October",
    startPoint: "Delhi",
    endPoint: "Delhi",
    overview: "The ultimate Grand Adi Kailash Yatra — a 9N/10D comprehensive spiritual expedition from Delhi covering everything: Adi Kailash Darshan, Om Parvat, Narayan Ashram, Panchachuli Valley trek, Patal Bhuvaneshwar, Gangolihat, Chitai Golju, Binsar Mahadev, Baijnath Dham, Jageshwar Dham's Kuber/Dandeshwar/Vridh Jageshwar, Kasar Devi, Katarmal Sun Temple, Mukteshwar, Kainchi Dham, and Nainital — a complete pilgrimage of Devbhoomi Uttarakhand.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable homestays/hotels (Twin/Triple sharing)" },
      { icon: Utensils, text: "10 Breakfasts & 9 Dinners (Pure Vegetarian)" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All interstate, road & local permits included" },
      { icon: Compass, text: "Dedicated local coordinator & basic first-aid kit" },
      { icon: Mountain, text: "All major Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, Heater, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services (Pay Directly if Required)",
      "Private/Single Room Stay (Available at Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra 4x4 vehicle cost in case of heavy snowfall",
    ],
    itinerary: [
      {
        day: 1,
        title: "Delhi → Pithoragarh",
        description: "Depart from Delhi at 6:00 AM towards the pure Himalayan air of Devbhoomi Uttarakhand. Flowing rivers, hidden waterfalls, and dense forests accompany the journey. Arrive at Pithoragarh (1,645 m) with panoramic views of snow-capped Panchachuli Peaks, lush valleys, and sacred Himalayan silence.",
        meals: "Breakfast & Dinner",
        overnight: "Pithoragarh",
        highlights: ["Panchachuli Peak views", "Himalayan forests", "Sacred Himalayan silence"],
      },
      {
        day: 2,
        title: "Pithoragarh – Dharchula – Nabhi / Gunji",
        description: "Drive to Dharchula along the Kali River with Nepal visible across the valley. Enjoy scenic off-roading via Himalayan villages passing waterfalls, deep gorges, and snow-clad peaks. Medical check-up and Inner Line Permit formalities completed en route. Arrive at Nabhi/Gunji Village.",
        meals: "Breakfast & Dinner",
        overnight: "Nabhi/Gunji/Napalchu Homestay",
        highlights: ["Kali River valley", "Nepal border views", "Inner Line Permit"],
      },
      {
        day: 3,
        title: "Nabhi/Gunji → Adi Kailash & Back",
        description: "Start early and trek toward the sacred Adi Kailash. Witness Kunti Parvat, Pandav Fort, and Brahma Parvat. At Adi Kailash Temple, perform prayers and take a holy dip in Parvati Sarovar. Marvel at Panda Parvat, Parvati Mukut, and Bheem Ki Kheti. Visit Manokamna Temple in Nabhi Village.",
        meals: "Breakfast & Dinner",
        overnight: "Gunji/Nepalchu Guesthouse",
        highlights: ["Adi Kailash Darshan", "Parvati Sarovar", "Gauri Kund", "Manokamna Temple"],
      },
      {
        day: 4,
        title: "Gunji/Nabhi → Om Parvat → Narayan Ashram",
        description: "Head to Om Parvat where the snow forms the sacred ॐ symbol. Enjoy darshan and meditation. Stop at Kala Pani for a group Hawan Puja near Kali Mandir and Vyas Gufa. If permitted, view Mount Kailash from Old Lipulekh Pass. Drive to Narayan Ashram — a serene Himalayan retreat.",
        meals: "Breakfast & Dinner",
        overnight: "Narayan Ashram",
        highlights: ["Om Parvat ॐ Darshan", "Hawan Puja at Kala Pani", "Vyas Gufa", "Narayan Ashram"],
      },
      {
        day: 5,
        title: "Narayan Ashram → Panchachuli Valley (Dharmavalli/Dugtu)",
        description: "Early morning explore Narayan Ashram campus, library & gardens. After breakfast, drive and short trek to Dugtu/Dantu/Dharmavalli, entering the remote Panchachuli Valley. Enjoy traditional village life, mountain views, and first close-up views of the magnificent Panchachuli Peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Dharmavalli / Dugtu Homestay",
        highlights: ["Narayan Ashram campus", "Panchachuli Valley entry", "Traditional Himalayan villages"],
      },
      {
        day: 6,
        title: "Panchachuli Base Area Trek",
        description: "Early morning easy hike towards the Panchachuli Base Area for close views of all five Panchachuli Peaks. Photography, nature walks, and local interaction amidst glacier views, alpine meadows, and untouched Himalayan nature.",
        meals: "Breakfast & Dinner",
        overnight: "Dharmavalli / Dugtu",
        highlights: ["Panchachuli I-V Base Views", "Glacier views", "Alpine meadows"],
      },
      {
        day: 7,
        title: "Dharmavalli → Dharchula → Patal Bhuvaneshwar → Gangolihat",
        description: "Drive through serene Himalayan valleys to Dharchula — witness the sacred India-Nepal border & Mahakali River confluence. Explore the mystical Patal Bhuvaneshwar cave temple described in the Skanda Purana. Visit Gangolihat's ancient temples for panoramic Himalayan peaks.",
        meals: "Breakfast & Dinner",
        overnight: "Gangolihat",
        highlights: ["Mahakali River confluence", "Patal Bhuvaneshwar Cave", "Gangolihat temples"],
      },
      {
        day: 8,
        title: "Gangolihat → Chitai Golu Devta → Jageshwar Dham",
        description: "Pass through Chitai Golju — perfect for meditation. Binsar Mahadev — sacred in pine forests with spiritual vibes. Baijnath Dham — ancient Shiva temple with Himalayan river backdrop. Arrive at Jageshwar Dham — over 100 ancient temples in cedar forests with a divine evening aura.",
        meals: "Breakfast & Dinner",
        overnight: "Jageshwar Dham",
        highlights: ["Chitai Golju Devta", "Binsar Mahadev", "Baijnath Dham", "Jageshwar Dham 100+ temples"],
      },
      {
        day: 9,
        title: "Jageshwar Dham → Kasar Devi → Bhowali",
        description: "Morning Darshan at Jageshwar Dham: Kuber Mandir, Dandeshwar Mahadev, and Vridh Jageshwar. After lunch, visit Kasar Devi Temple (Van Allen Belt energy zone, visited by Swami Vivekananda), Katarmal Sun Temple (older than Konark), and Nanda Devi Temple, Almora. Overnight stay at Bhowali.",
        meals: "Breakfast & Dinner",
        overnight: "Bhowali",
        highlights: ["Jageshwar Darshan", "Kuber Mandir", "Dandeshwar Mahadev", "Kasar Devi", "Katarmal Sun Temple"],
      },
      {
        day: 10,
        title: "Bhowali → Mukteshwar → Kainchi Dham → Nainital → Delhi",
        description: "Breakfast at Bhowali, then visit Bahugarh Waterfall, explore Mukteshwar, Choli ki Jali, and the scenic Tea Garden. Darshan at Kainchi Dham (Neem Karoli Baba's ashram), Kakdi Ghat, Hanuman Garhi. Visit Nainital — Naini Lake & local sightseeing. Begin the return journey to Delhi with divine blessings.",
        meals: "Breakfast & Dinner",
        overnight: "Journey concludes at Delhi",
        highlights: ["Bahugarh Waterfall", "Mukteshwar", "Kainchi Dham", "Hanuman Garhi", "Nainital Naini Lake"],
      },
    ],
    highlights: [
      "Adi Kailash Darshan & Parvati Sarovar holy dip",
      "Om Parvat — Natural ॐ snow formation",
      "Panchachuli Valley trek via Narayan Ashram",
      "Patal Bhuvaneshwar — Mystical cave temple",
      "Jageshwar Dham + Kasar Devi + Katarmal Sun Temple",
      "Kainchi Dham & Nainital — Grand finale",
    ],
    spiritualSignificance: "The grandest Devbhoomi spiritual circuit. Adi Kailash is Lord Shiva's earthly abode. Narayan Ashram is a meditation haven. Patal Bhuvaneshwar's single darshan grants Char Dham punya. Kasar Devi lies on a Van Allen Belt energy zone. Katarmal Sun Temple is 400 years older than Konark. Jageshwar Dham is the origin of Shiva worship. Kainchi Dham offers Neem Karoli Baba's divine grace. A complete pilgrimage of the soul.",
  },
  {
    id: "kainchi-dham",
    title: "Kainchi Dham Himalayan Retreat",
    subtitle: "2 Nights / 3 Days — Delhi to Delhi",
    image: "/images/kainchi-dham.jpg",
    heroImage: "/images/kainchi-dham.jpg",
    duration: "2 Nights / 3 Days",
    category: "Kainchi Dham",
    nights: 2,
    groupSize: "Group Tour",
    difficulty: "Easy",
    bestSeason: "Year Round",
    startPoint: "Anand Vihar Bus Terminal, Delhi",
    endPoint: "Anand Vihar Bus Terminal, Delhi",
    overview: "Take a break from the noise of city life and let the Himalayas heal your soul. The Himalayan Retreat is a perfect blend of spiritual blessings, nature's serenity, and refreshing leisure. From the divine aura of Kainchi Dham to the tranquil lakes of Naukuchiatal, Bhimtal, and Sattal, and the lively charm of Nainital — this short getaway offers peace for devotees and joy for travelers alike.",
    inclusions: [
      { icon: Hotel, text: "Clean & comfortable hotel/resort (Twin/Triple sharing)" },
      { icon: Utensils, text: "2 Breakfasts & 1 Dinner (Pure Vegetarian)" },
      { icon: MapPin, text: "Comfortable AC Force Tempo Traveller" },
      { icon: ShieldCheck, text: "All permits & taxes included" },
      { icon: Compass, text: "Dedicated tour coordinator & first-aid kit" },
      { icon: Mountain, text: "All Darshan & sightseeing as per itinerary" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, etc.)",
      "Lunch not included",
      "Individual Seat Preference Not Guaranteed",
      "Porter/Pony Services",
      "Private Room Stay (Available at Extra Cost)",
      "Medical Emergency or Evacuation Costs",
    ],
    itinerary: [
      {
        day: 1,
        title: "Night Departure from Delhi",
        description: "Assemble at Anand Vihar Bus Terminal by 9:30 PM. Meet your tour coordinator & fellow travelers. 10:00 PM departure for Naukuchiatal (approx. 8–9 hour overnight journey). Enjoy music and light snacks as you leave behind the city chaos for the calm of Kumaon Hills.",
        meals: "No meals",
        overnight: "Overnight journey",
      },
      {
        day: 2,
        title: "Kainchi Dham • Sattal • Bhimtal • Naukuchiatal",
        description: "Morning arrival at Naukuchiatal. Check-in at Himalayan Lake View Resort. Freshen up and enjoy breakfast. 10:00 AM — Depart for Kainchi Dham for Baba Neem Karoli Maharaj's divine blessings. 2:00 PM — Visit Sattal (seven serene lakes) for boating, kayaking. Later, visit Bhimtal with its majestic lake and island temple. 7:00 PM — Evening Celebration with open mic, music, and gathering under the stars.",
        meals: "Breakfast & Dinner",
        overnight: "Naukuchiatal Resort",
        highlights: ["Kainchi Dham Darshan", "Sattal Lake Boating", "Bhimtal Island Temple", "Evening Celebration"],
      },
      {
        day: 3,
        title: "Naukuchiatal • Nainital • Return to Delhi",
        description: "Wake up to cool mountain breeze and enjoy lakeside breakfast. Visit Mouni Mai Ashram, Vaishno Devi Cave, and Hanuman Temple. Continue to Nainital — explore Naini Lake, Naina Devi Temple, Mall Road, Tibetan Market, Snow View Point. 5:00 PM — Group assembly and departure for Delhi. Arrive ~10:00 PM at Anand Vihar Bus Terminal.",
        meals: "Breakfast",
        overnight: "Journey concludes",
        highlights: ["Mouni Mai Ashram", "Nainital sightseeing", "Naini Lake", "Mall Road"],
      },
    ],
    highlights: [
      "Darshan at Kainchi Dham — Baba Neem Karoli Maharaj",
      "Stay at a Himalayan Lake Retreat",
      "Boating & Kayaking at Sattal & Bhimtal",
      "Nature, Music & Meditation in the Himalayas",
      "Perfect for Bhakts, explorers & peace-seekers",
      "Evening Celebration & Group Dinner in the Hills",
    ],
  },
  {
    id: "kinner-kailash",
    title: "Kinner Kailash Trek",
    subtitle: "4 Days — Ex. Shimla",
    image: "/images/kinner-kailash.jpg",
    heroImage: "/images/kinner-kailash.jpg",
    duration: "4 Days",
    category: "Kinner Kailash",
    nights: 3,
    groupSize: "Max 15 People",
    distance: "Approx 32 KM",
    maxAltitude: "4,885m / 16,025 ft",
    difficulty: "Difficult",
    bestSeason: "June – September (Summer)",
    startPoint: "Old Busstand, Shimla",
    endPoint: "Shimla",
    overview: "A sacred and challenging trek to the revered Kinner Kailash, passing through dense pine forests, lush meadows, and rugged rocky paths. The journey tests trekkers with steep ascents and tough terrain, offering breathtaking Himalayan views. Located in the Kinnaur region of Himachal Pradesh, its spiritual significance, natural beauty, and thrilling adventure make it an unforgettable experience.",
    inclusions: [
      { icon: Hotel, text: "Homestay at Reckong Peo + Camps (2/3 per tent)" },
      { icon: Utensils, text: "All meals from Day 1 Dinner to Day 4 Breakfast (Vegetarian)" },
      { icon: MapPin, text: "7-seater SUV transport (Shimla to Peo & back)" },
      { icon: ShieldCheck, text: "All trekking permits & forest camping charges" },
      { icon: Compass, text: "High quality tents, sleeping bags, ice axes, ropes, micro spikes" },
      { icon: Mountain, text: "First aid, high altitude medical kit, oxygen cylinders" },
    ],
    exclusions: [
      "Personal expenses (extra meals, beverages, laundry)",
      "Rescue costs (emergency evacuation, hospitalization)",
      "Unforeseen expenses due to natural calamities",
      "Offloading luggage (available at extra cost)",
      "Rental gear (available at fraction of purchase cost)",
    ],
    itinerary: [
      {
        day: 1,
        title: "Shimla to Reckong Peo",
        description: "Drive from Shimla Old Busstand to Reckong Peo through scenic Himalayan roads. 220 km drive taking 6-7 hours. Arrive at Reckong Peo at 2,276m altitude, check into local homestay and rest for the trek ahead.",
        meals: "Dinner",
        overnight: "Reckong Peo Homestay",
        highlights: ["Scenic Himalayan drive", "Kinnaur Valley views"],
      },
      {
        day: 2,
        title: "Reckong Peo → Tallangpi → Ganesh Park Trek",
        description: "Drive 15 km (1 hour) to Tallangpi, the trek starting point. Begin the 7 km trek through dense pine forests and alpine meadows for 5-6 hours reaching Ganesh Park at 3,810m. Set up camp surrounded by towering peaks.",
        meals: "Breakfast, Lunch & Dinner",
        overnight: "Ganesh Park Camp",
        highlights: ["Pine forest trails", "Alpine meadows", "3,810m campsite"],
      },
      {
        day: 3,
        title: "Ganesh Park to Shivling & Back to Camp",
        description: "The most challenging day — 18 km round trek taking 10-12 hours. Ascend to the sacred Shivling at the maximum altitude of 4,885m (16,025 ft). Navigate through rocky terrain, steep paths, and high-altitude conditions. Darshan at the sacred Kinner Kailash Shivling, then return to camp.",
        meals: "Breakfast, Lunch & Dinner",
        overnight: "Ganesh Park Camp",
        highlights: ["Kinner Kailash Shivling Darshan", "4,885m summit", "Panoramic Himalayan views"],
      },
      {
        day: 4,
        title: "Ganesh Park → Tallangpi → Drive to Shimla",
        description: "Descend 7 km trek (4-5 hours) back to Tallangpi through the forests. Then a long 230 km drive (10 hours) back to Shimla. The trek concludes with unforgettable memories of the sacred Kinner Kailash.",
        meals: "Breakfast",
        overnight: "Journey concludes at Shimla",
        highlights: ["Descent through forests", "Return to Shimla"],
      },
    ],
    highlights: [
      "Sacred Kinner Kailash Shivling at 16,025 ft",
      "Dense pine forests & lush alpine meadows",
      "Kinnaur region — one of the most beautiful in India",
      "Trek Completion Certificate provided",
      "Professional safety equipment & guides",
      "Breathtaking panoramic Himalayan views",
    ],
    price: "₹9,499",
    mandatoryItems: [
      "Trekking Shoes (High Ankle)", "50+ L Rucksack", "Warm Clothes (Layering)", "Trek Pants",
      "Fleece & Padded Jacket", "Raincoat/Poncho", "Winter Gloves", "Woollen Socks",
      "Water Bottles (2x 1L)", "Trek Poles", "Head Lamp", "Power Bank", "Sun Cap",
      "UV Sunglasses", "Sunscreen", "Medical Kit (Diamox, Dolo, ORS, Combiflam)",
    ],
  },
  {
    id: "manimahesh-kailash",
    title: "Manimahesh Kailash Yatra",
    subtitle: "6 Nights / 7 Days — Pathankot/Amritsar",
    image: "/images/manimahesh.jpg",
    heroImage: "/images/manimahesh.jpg",
    duration: "6 Nights / 7 Days",
    category: "Manimahesh",
    nights: 6,
    groupSize: "Group / Individual / Family",
    distance: "465 km Round Trip",
    maxAltitude: "13,390 ft (4,080m)",
    difficulty: "Very Difficult",
    bestSeason: "August – September",
    startPoint: "Pathankot / Amritsar",
    endPoint: "Pathankot / Amritsar",
    overview: "Nestled in the sacred Pir Panjal ranges of Himachal Pradesh at approximately 4,080 meters, Shri Manimahesh Dham is revered as the divine abode of Lord Shiva. It is believed that after his celestial marriage with Goddess Parvati, Lord Shiva manifested this holy lake. The reflection of the majestic Manimahesh Kailash Peak in the crystal-clear waters is considered a living symbol of Mahadev's presence.",
    inclusions: [
      { icon: Hotel, text: "Homestays/Hotels/Camps (Twin/Triple Sharing)" },
      { icon: Utensils, text: "7 Breakfasts & 6 Dinners + Tea, Coffee, Soup during trek" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls, parking & driver" },
      { icon: ShieldCheck, text: "All permits, Oxygen Can & Pulse Oximeter monitoring" },
      { icon: Compass, text: "Experienced Trek Guide & local coordinator" },
      { icon: Footprints, text: "Porter Support (1 porter for 3 persons)" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses (Laundry, Snacks, Room Service, etc.)",
      "Individual Seat Preference in Vehicle Not Guaranteed",
      "Porter/Pony Services beyond included support",
      "Private/Single Room Stay (Extra Cost)",
      "Medical Emergency, Rescue or Evacuation Costs",
      "Extra Stay: ₹3,499 per person per night (if trek extends)",
    ],
    itinerary: [
      {
        day: 1,
        title: "Pathankot/Amritsar → Bharmour",
        description: "Arrival at Pathankot Railway Station or Amritsar Airport. Meet the SKR Tour & Travels representative and drive approximately 180 km (7-8 hrs) towards Bharmour through the scenic Chamba Valley. Enjoy the natural beauty en route. Leisure time to explore the peaceful beauty of Bharmour.",
        meals: "Dinner",
        overnight: "Bharmour Hotel/Homestay",
        highlights: ["Scenic Chamba Valley drive", "Bharmour exploration"],
      },
      {
        day: 2,
        title: "Bharmour – Kugti – Kartik Swami Mandir",
        description: "After breakfast, drive to Kugti Village (26 km) inside Kugti Wildlife Sanctuary. Explore the untouched natural beauty of the Bharmour-Kugti region. Begin the 8 km round trek to the sacred Kartik Swami Temple dedicated to Lord Kartikeya & Marali Mata Mandir. Return to Bharmour by evening.",
        meals: "Breakfast & Dinner",
        overnight: "Bharmour",
        highlights: ["Kugti Wildlife Sanctuary", "Kartik Swami Temple Trek", "Marali Mata Mandir"],
      },
      {
        day: 3,
        title: "Bharmour Spiritual Sightseeing",
        description: "Visit Bharmani Mata Temple (taxi + short trek). Explore the Chaurasi Temple Complex — an ancient cluster of 84 temples. Darshan at Dharmaraj (Chitragupt) Temple. Attend the evening aarti. Spend time absorbing the serene spiritual and natural beauty of Bharmour and the Chamba region.",
        meals: "Breakfast & Dinner",
        overnight: "Bharmour",
        highlights: ["Bharmani Mata Temple", "Chaurasi Temple Complex", "Dharmaraj Temple", "Evening Aarti"],
      },
      {
        day: 4,
        title: "Bharmour → Hadsar → Dhancho Trek",
        description: "Drive to Hadsar (13 km), the base of Manimahesh Yatra. Trek approximately 6 km through scenic Himalayan trails to reach Dhancho while enjoying the raw mountain beauty of the Bharmour Himalayas.",
        meals: "Breakfast & Dinner",
        overnight: "Dhancho Camp",
        highlights: ["Hadsar base camp", "6 km Himalayan trek", "Dhancho campsite"],
      },
      {
        day: 5,
        title: "Dhancho → Manimahesh Lake → Dhancho",
        description: "Early morning trek of approximately 7 km to the sacred Manimahesh Lake at 13,000 ft. Take a holy dip in the lake. Darshan of Shri Manimahesh Kailash Peak. Offer prayers to Lord Shiva. Return trek to Dhancho camp.",
        meals: "Breakfast & Dinner",
        overnight: "Dhancho Camp",
        highlights: ["Manimahesh Lake Holy Dip", "Kailash Peak Darshan", "Prayers to Lord Shiva"],
      },
      {
        day: 6,
        title: "Dhancho → Hadsar → Bharmour",
        description: "Descend trek to Hadsar and drive back to Bharmour. Relax and enjoy local Himachali cuisine. Take time to admire the peaceful beauty of Bharmour and the wider Chamba Valley one last time.",
        meals: "Breakfast & Dinner",
        overnight: "Bharmour",
        highlights: ["Descent trek", "Himachali cuisine", "Chamba Valley views"],
      },
      {
        day: 7,
        title: "Bharmour → Pathankot / Amritsar",
        description: "After breakfast, departure for Pathankot or Amritsar with divine blessings. The tour concludes with SKR Tour & Travels. Har Har Mahadev!",
        meals: "Breakfast",
        overnight: "Journey concludes",
        highlights: ["Return journey", "Divine blessings"],
      },
    ],
    highlights: [
      "Sacred Manimahesh Lake at 13,000 ft",
      "Manimahesh Kailash Peak Darshan",
      "Holy dip for spiritual purification",
      "Chaurasi Temple Complex — 84 ancient temples",
      "Kugti Wildlife Sanctuary",
      "Kartik Swami Temple Trek",
    ],
    spiritualSignificance: "The name Manimahesh is derived from Mani (Divine Jewel) and Mahesh (Lord Shiva). Devotees believe that on auspicious full-moon nights, a mystical jewel shines atop the peak. A holy dip in Manimahesh Lake purifies the soul and grants spiritual merit comparable to the Kailash Mansarovar Yatra.",
    mandatoryItems: [
      "Trekking Shoes (High Ankle)", "40-50 L Backpack", "Warm Clothes (Layering)", "Trek Pants",
      "Sweater", "Heavy Jacket", "Raincoat/Poncho", "Winter Gloves", "Woollen Socks",
      "Water Bottle", "Trekking Stick", "Head Torch", "Power Bank", "Sun Cap", "UV Sunglasses",
    ],
  },
  {
    id: "srikhand-kailash-chandigarh",
    title: "Srikhand Kailash Yatra (Chandigarh)",
    subtitle: "6 Nights / 7 Days — Chandigarh to Chandigarh with Shimla",
    image: "/images/shrikhand-1.jpg",
    heroImage: "/images/shrikhand-1.jpg",
    duration: "6 Nights / 7 Days",
    category: "Srikhand Kailash",
    nights: 6,
    groupSize: "Group / Individual",
    distance: "34 km (One Side Trek)",
    maxAltitude: "18,500 ft (5,639m)",
    difficulty: "Very Difficult",
    bestSeason: "July – August",
    startPoint: "Chandigarh",
    endPoint: "Chandigarh",
    overview: "Shrikhand Mahadev Kailash is one of the five sacred Kailash peaks and is considered among the most challenging Himalayan pilgrimages. Located at approximately 18,500 ft, this divine Shivalinga-shaped rock peak stands tall in the Himalayas of Himachal Pradesh. The total trekking distance is 34 km one way, mostly steep ascent through glaciers, rocky terrain, narrow ridges, and high-altitude passes. This yatra demands strong physical endurance, mental strength, and deep spiritual devotion.",
    inclusions: [
      { icon: Hotel, text: "Homestays/Camps (Twin/Triple Sharing)" },
      { icon: Utensils, text: "Daily Breakfast & Dinner + Tea, Coffee, Soup on trek" },
      { icon: MapPin, text: "Well-maintained vehicle with tolls & parking" },
      { icon: ShieldCheck, text: "All permits, Oxygen Can & Pulse Oximeter" },
      { icon: Compass, text: "Experienced Trek Guide & coordinator" },
      { icon: Footprints, text: "Porter Support (1 porter for 2 persons)" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses",
      "Porter/Pony beyond included support",
      "Private Room Stay (Extra Cost)",
      "Medical Emergency or Evacuation Costs",
      "Extra Stay: ₹3,499 per person per night",
    ],
    itinerary: [
      {
        day: 1,
        title: "Chandigarh – Nirmand – Jaon Village",
        description: "Departure from Chandigarh towards the sacred Himalayan region. Darshan at Dev Dhank Mandir — an ancient temple of Lord Shiva believed to be spiritually connected with Shrikhand Mahadev's divine energy. Visit Shelashni Mata Mandir — a powerful Shakti shrine where pilgrims pray for protection. Arrival at Jaon Village, the base village of Shrikhand Mahadev Yatra.",
        meals: "Dinner",
        overnight: "Jaon Village Homestay",
        highlights: ["Dev Dhank Mandir", "Shelashni Mata Mandir", "Jaon Village"],
      },
      {
        day: 2,
        title: "Jaon to Thachru (14 km Trek)",
        description: "After breakfast, the trek begins from Jaon. Key spiritual & scenic points: Singhad Base, Barati Nala (challenging water crossing), 30 Wheel Point (steep zig-zag climb), and Thachru — a beautiful alpine meadow and famous camping site surrounded by dense forests and Himalayan beauty.",
        meals: "Breakfast & Dinner",
        overnight: "Thachru Camps (Sharing)",
        highlights: ["Singhad Base", "Barati Nala Crossing", "30 Wheel Point", "Alpine meadows"],
      },
      {
        day: 3,
        title: "Thachru to Bhim Dwari (13 km Trek)",
        description: "Today's route includes Kali Top / Kali Ghati (narrow ridge, spiritually powerful point), Bhim Talai (named after Bhima from Mahabharata), Kunsha Valley (scenic high-altitude meadow), Parvati Bagh (rare high-altitude flowers), and Nayan Sarovar (sacred glacial lake). Arrival at Bhim Dwari — mythologically the resting place of Bhima.",
        meals: "Breakfast & Dinner",
        overnight: "Bhim Dwari Camps",
        highlights: ["Kali Top", "Bhim Talai", "Parvati Bagh", "Nayan Sarovar"],
      },
      {
        day: 4,
        title: "Bhim Dwari → Shrikhand Mahadev Darshan & Back (18 km)",
        description: "The most important and toughest day. The route includes glacier crossings, rocky patches, and high-altitude exposure. Early morning departure. Darshan at the sacred Shrikhand Mahadev peak (18,500 ft). Spiritual time for prayers. Return back to Bhim Dwari. Weather can change rapidly at this altitude.",
        meals: "Breakfast & Dinner",
        overnight: "Bhim Dwari Camps",
        highlights: ["Shrikhand Mahadev Darshan at 18,500 ft", "Glacier crossings", "High-altitude prayers"],
      },
      {
        day: 5,
        title: "Bhim Dwari to Thachru (Descent)",
        description: "Careful descent back through the same route. Retrace the beautiful trails through Parvati Bagh and Kali Ghati. Rest and recovery at Thachru camps.",
        meals: "Breakfast & Dinner",
        overnight: "Thachru Camps",
      },
      {
        day: 6,
        title: "Thachru to Jaon (Final Descent)",
        description: "Final descent through forest & mountain trails back to Jaon village. Experience the changing landscape as you descend from alpine meadows to dense forests. Overnight stay at Jaon Village homestay.",
        meals: "Breakfast & Dinner",
        overnight: "Jaon Village Homestay",
      },
      {
        day: 7,
        title: "Jaon → Narkanda → Shimla → Chandigarh",
        description: "After breakfast, the return journey begins through the serene heights of Narkanda with a sacred stop at Hatu Temple — an ancient hilltop shrine. Further ahead in Shimla, seek blessings at Jakhu Temple, dedicated to Lord Hanuman. Continue to Chandigarh where the yatra concludes. You arrived as a devotee… you return as a true Shiv Kailashi! 🔱",
        meals: "Breakfast",
        overnight: "Journey concludes at Chandigarh",
        highlights: ["Hatu Temple", "Jakhu Temple Shimla", "Narkanda scenic drive"],
      },
    ],
    highlights: [
      "Shrikhand Mahadev — one of five sacred Kailash peaks",
      "Summit at 18,500 ft — Shivalinga-shaped rock peak",
      "34 km trek through glaciers & high-altitude passes",
      "Sacred glacial lakes — Nayan Sarovar",
      "Parvati Bagh — rare high-altitude flower region",
      "Hatu Temple & Jakhu Temple Shimla sightseeing",
    ],
    spiritualSignificance: "Shrikhand Mahadev is one of the five sacred Kailash peaks. It is believed that Lord Shiva meditated here for thousands of years. Every step of this sacred route carries mythological and spiritual significance. The Shivalinga-shaped peak at 18,500 ft is the ultimate symbol of divine power.",
    mandatoryItems: [
      "Trekking Shoes (High Ankle)", "40-50 L Backpack", "Warm Clothes (Layering)", "Trek Pants",
      "Sweater", "Heavy Jacket", "Raincoat/Poncho", "Winter Gloves", "Woollen Socks",
      "Water Bottle", "Trekking Stick", "Head Torch", "Power Bank", "Sun Cap", "UV Sunglasses",
    ],
  },
  {
    id: "srikhand-kailash-jaon",
    title: "Srikhand Kailash Yatra (Jaon)",
    subtitle: "5 Nights / 6 Days — Jaon to Jaon",
    image: "/images/shrikhand-2.jpg",
    heroImage: "/images/shrikhand-2.jpg",
    duration: "5 Nights / 6 Days",
    category: "Srikhand Kailash",
    nights: 5,
    groupSize: "Group / Individual",
    distance: "34 km (One Side Trek)",
    maxAltitude: "18,500 ft (5,639m)",
    difficulty: "Very Difficult",
    bestSeason: "July – August",
    startPoint: "Jaon Village",
    endPoint: "Jaon Village",
    overview: "Shrikhand Mahadev Kailash is one of the five sacred Kailash peaks and is considered among the most challenging Himalayan pilgrimages. This is the direct trek package starting from Jaon Village — the base of Shrikhand Mahadev. The divine Shivalinga-shaped rock peak at 18,500 ft demands strong physical endurance, mental strength, and deep spiritual devotion.",
    inclusions: [
      { icon: Hotel, text: "Homestays/Camps (Twin/Triple Sharing)" },
      { icon: Utensils, text: "Daily Breakfast & Dinner + Tea, Coffee, Soup" },
      { icon: MapPin, text: "Well-maintained vehicle as per itinerary" },
      { icon: ShieldCheck, text: "All permits, Oxygen Can & Pulse Oximeter" },
      { icon: Compass, text: "Experienced Trek Guide & coordinator" },
      { icon: Footprints, text: "Porter Support (1 porter for 2 persons)" },
    ],
    exclusions: [
      "Travel, Health or Accidental Insurance",
      "Personal Expenses",
      "Porter/Pony beyond included support",
      "Private Room Stay (Extra Cost)",
      "Medical Emergency or Evacuation Costs",
      "Extra Stay: ₹3,499 per person per night",
    ],
    itinerary: [
      {
        day: 1,
        title: "Yatra Start from Jaon",
        description: "Visit Shelashni Mata Mandir — a powerful Shakti shrine where pilgrims pray for protection and success in completing the sacred journey to Shrikhand Mahadev. It is believed that Mata's blessings safeguard every devotee on this challenging spiritual path. Overnight stay at Jaon Village (homestay).",
        meals: "Dinner",
        overnight: "Jaon Village Homestay",
        highlights: ["Shelashni Mata Mandir Darshan"],
      },
      {
        day: 2,
        title: "Jaon to Thachru (14 km Trek)",
        description: "After breakfast, the trek begins from Jaon. Key spiritual & scenic points: Singhad Base, Barati Nala (challenging water crossing), 30 Wheel Point (steep zig-zag climb). Thachru (Thachadu) is a beautiful alpine meadow and famous camping site surrounded by dense forests and Himalayan beauty.",
        meals: "Breakfast & Dinner",
        overnight: "Thachru Camps (Sharing)",
        highlights: ["Singhad Base", "Barati Nala", "30 Wheel Point", "Alpine meadows"],
      },
      {
        day: 3,
        title: "Thachru to Bhim Dwari (13 km Trek)",
        description: "Route includes Kali Top / Kali Ghati (narrow ridge), Bhim Talai, Kunsha Valley, Parvati Bagh (rare high-altitude flowers), and Nayan Sarovar (sacred glacial lake). Arrival at Bhim Dwari — the mythological resting place of Bhima.",
        meals: "Breakfast & Dinner",
        overnight: "Bhim Dwari Camps",
        highlights: ["Kali Top", "Bhim Talai", "Parvati Bagh", "Nayan Sarovar"],
      },
      {
        day: 4,
        title: "Bhim Dwari → Shrikhand Mahadev & Back (18 km)",
        description: "The most important and toughest day with glacier crossings, rocky patches, and high-altitude exposure. Early morning departure to the sacred Shrikhand Mahadev peak at 18,500 ft. Spiritual time for prayers and darshan. Return to Bhim Dwari.",
        meals: "Breakfast & Dinner",
        overnight: "Bhim Dwari Camps",
        highlights: ["Shrikhand Mahadev Darshan", "18,500 ft summit", "Glacier crossings"],
      },
      {
        day: 5,
        title: "Bhim Dwari to Thachru",
        description: "Careful descent back through the majestic Himalayan trails. Rest and recovery at Thachru camps.",
        meals: "Breakfast & Dinner",
        overnight: "Thachru Camps",
      },
      {
        day: 6,
        title: "Thachru to Jaon — Journey Ends",
        description: "Final descent through forest & mountain trails back to Jaon. After breakfast, the sacred journey concludes with Lord Shiva's divine blessings. Blessed are you, for the rare darshan of Shrikhand Kailash has touched your soul. You return not just as a traveler, but as a true Shiv Kailashi — forever transformed.",
        meals: "Breakfast",
        overnight: "Journey concludes at Jaon",
      },
    ],
    highlights: [
      "Shrikhand Mahadev — sacred Shivalinga at 18,500 ft",
      "34 km trek through glaciers & rocky terrain",
      "Sacred Nayan Sarovar — glacial lake",
      "Parvati Bagh — rare high-altitude flowers",
      "Shelashni Mata Mandir blessings",
      "Test of faith, endurance & spiritual devotion",
    ],
    spiritualSignificance: "Shrikhand Kailash is not just a trek — it is a test of faith, endurance, and surrender to Lord Shiva amidst raw Himalayan beauty. The Shivalinga-shaped peak stands as a divine symbol visible only to those who undertake this extreme pilgrimage.",
    mandatoryItems: [
      "Trekking Shoes (High Ankle)", "40-50 L Backpack", "Warm Clothes (Layering)", "Trek Pants",
      "Sweater", "Heavy Jacket", "Raincoat/Poncho", "Winter Gloves", "Woollen Socks",
      "Water Bottle", "Trekking Stick", "Head Torch", "Power Bank", "Sun Cap", "UV Sunglasses",
    ],
  },
];
